modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
modId = "netmusic"
version = "${file.jarVersion}"
displayName = "Net Music Mod"
authors = "TartaricAcid, 郝南村, 琥珀酸, 帕金伊, SQwatermark"
description = "A music player mod"

[[dependencies.netmusic]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netmusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netmusic]]
modId = "touhou_little_maid"
mandatory = false
versionRange = "[1.1.5,)"
ordering = "AFTER"
side = "BOTH"
